name: Build Documentation for PRs
on:
  pull_request:
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build documentation
      run: |
        sudo snap install yq
        cd docs
        make all
